import { Fragment } from 'react'
import { ArrowRight, BrainCircuit, CheckCircle2, SearchCheck, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import ResultCard from '../components/ResultCard'
import { demoResults } from '../data/mockData'

const features = [[Zap, 'Real-time analysis', 'Analyze suspicious URLs quickly using lightweight URL-based feature extraction.'], [BrainCircuit, 'ML-powered detection', 'Machine learning evaluates lexical and structural URL patterns to identify phishing risk.'], [SearchCheck, 'Explainable results', 'Understand why a URL was flagged through transparent risk factors.']]
const Flow = ({ modern }) => <div className="flow">{(modern ? ['URL input', 'Validation', '20+ features', 'ML model', 'Risk score', 'Explainable verdict'] : ['URL', 'Blacklist database', 'Known?', 'Allow or block']).map((item, index, arr) => <Fragment key={item}><div>{item}</div>{index < arr.length - 1 && <span>↓</span>}</Fragment>)}</div>
export default function Home() { return <><main><section className="hero shell"><div className="hero-copy"><div className="announce"><Sparkles size={15}/> URL intelligence, not website execution</div><h1>Detect phishing <span>before you click.</span></h1><p>Analyze suspicious URLs using machine learning and 20+ lexical and structural features — without opening the target webpage.</p><div className="hero-actions"><Link className="button button-primary" to="/analyze">Analyze a URL <ArrowRight size={18}/></Link><Link className="button button-secondary" to="/how-it-works">How it works</Link></div><div className="trust-row"><span><CheckCircle2 size={17}/> No webpage loading</span><span><CheckCircle2 size={17}/> Explainable signals</span></div></div><div className="hero-visual"><div className="scan-orbit orbit-one"></div><div className="scan-orbit orbit-two"></div><ResultCard result={demoResults.phishing} compact /></div></section>
<section className="feature-section shell"><div className="center-heading"><span className="eyebrow">Made for safer decisions</span><h2>Clarity when a link feels off</h2><p>Useful security intelligence, expressed in language people can act on.</p></div><div className="feature-cards">{features.map(([Icon, title, text]) => <article className="feature-card card" key={title}><span className="feature-icon"><Icon size={21}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="comparison-section"><div className="shell"><div className="center-heading"><span className="eyebrow">A smarter signal</span><h2>Beyond known-bad lists</h2><p>Designed to identify suspicious URL structures, including previously unseen patterns.</p></div><div className="comparison-grid"><article className="comparison-card card"><span className="comparison-label">Traditional approach</span><h3>Reputation first</h3><Flow/><p>Previously unseen phishing URLs may not yet have reputation history.</p></article><article className="comparison-card card featured"><span className="comparison-label">PhishShield AI</span><h3>Structure-aware analysis</h3><Flow modern/><p>Combines validation, URL signals, and a model score into an explainable verdict.</p></article></div></div></section>
<section className="home-cta shell"><div><span className="eyebrow">Ready when you are</span><h2>Give a suspicious link a second opinion.</h2><p>PhishShield analyzes URL information without opening the target webpage.</p></div><Link className="button button-primary" to="/analyze">Start an analysis <ArrowRight size={18}/></Link></section></main></> }
