import { AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Database, ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import { riskMeta } from '../config'

const verdictMeta = { safe: { icon: CheckCircle2, label: 'Safe' }, suspicious: { icon: AlertTriangle, label: 'Suspicious' }, phishing: { icon: ShieldAlert, label: 'Phishing' } }
const titleize = (key) => key.replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase())
export default function ResultCard({ result, compact = false }) {
  const [showVector, setShowVector] = useState(false)
  const verdict = verdictMeta[result.verdict] || verdictMeta.suspicious
  const Icon = verdict.icon; const risk = riskMeta(result.risk_score); const confidence = result.confidence == null ? null : Math.round(result.confidence <= 1 ? result.confidence * 100 : result.confidence)
  return <section className={`result-stack ${compact ? 'compact' : ''}`}><article className={`result-card card tone-${risk.tone}`}><div className="result-top"><div><span className="eyebrow">Threat analysis</span><h2>{result.url}</h2></div><span className={`verdict-pill ${risk.tone}`}><Icon size={16}/>{verdict.label}</span></div><div className="result-main"><div className="gauge" style={{ '--score': `${result.risk_score * 3.6}deg` }}><div><strong>{result.risk_score}</strong><span>/ 100</span><em>{risk.label}</em></div></div><div className="result-summary"><span className="score-label">Risk score</span><h3>{risk.description}</h3><div className="metrics"><div><span>Confidence</span><b>{confidence == null ? '—' : `${confidence}%`}</b></div>{result.processing_time_ms && <div><span>Analysis time</span><b>{result.processing_time_ms} ms</b></div>}</div></div></div></article>
    {!compact && <><section className="reasons card"><div className="section-heading"><div><span className="eyebrow">Explainable AI</span><h3>Why was this URL flagged?</h3></div></div>{result.top_reasons.length ? <div className="reason-list">{result.top_reasons.slice(0, 3).map((reason) => <div key={reason}><AlertTriangle size={18}/><span>{reason}</span></div>)}</div> : <p>No explanation details were returned.</p>}</section>
    <section className="features card"><div className="section-heading"><div><span className="eyebrow">URL feature analysis</span><h3>Signals used in the assessment</h3></div><span className="feature-count">{Object.keys(result.features).length} available</span></div><div className="feature-grid">{Object.entries(result.features).map(([key, value]) => <div className="feature" key={key}><span>{titleize(key)}</span><b>{typeof value === 'boolean' ? (value ? 'Yes' : 'No') : value}</b></div>)}</div><button className="vector-toggle" onClick={() => setShowVector(!showVector)}><Database size={16}/> View feature vector {showVector ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}</button>{showVector && <div className="vector-table">{Object.entries(result.features).map(([key, value]) => <div key={key}><code>{key}</code><span>{String(value)}</span></div>)}</div>}</section>
    <section className="pipeline card"><div className="section-heading"><div><span className="eyebrow">Analysis pipeline</span><h3>How the verdict was reached</h3></div></div><div className="pipeline-row">{['URL', 'Validation', 'Features', 'ML classifier', 'Risk score', 'Verdict'].map((item, i) => <div key={item}><span>{i + 1}</span><b>{item}</b></div>)}</div></section></>}</section>
}
